import type { Diagnostic, ScanResult, Severity } from "../core/types.js";

function cleanCell(text?: string | null): string {
  if (!text) return "-";
  return text.replace(/\|/g, "\\|").replace(/\r?\n/g, " ").trim();
}

function severityBadge(severity: Severity): string {
  switch (severity) {
    case "critical":
      return "🔴 **Critical**";
    case "warning":
      return "🟡 **Warning**";
    case "info":
      return "🔵 **Info**";
    case "success":
      return "🟢 **Success**";
  }
}

export function generateMarkdownReport(result: ScanResult): string {
  const counts = { critical: 0, warning: 0, info: 0, success: 0 };
  for (const d of result.diagnostics) {
    counts[d.severity] += 1;
  }

  const issues = result.diagnostics.filter((d) => d.severity !== "success");
  const passed = result.diagnostics.filter((d) => d.severity === "success");

  const isPassed = counts.critical === 0;
  const statusText = isPassed ? "✅ **Passed**" : "❌ **Action Required**";
  const scorePercent = `${result.health.score}/100 (${result.health.grade.toUpperCase()})`;
  const secScore = result.health.securityScore ?? result.health.score;
  const secGrade = (result.health.securityGrade ?? result.health.grade).toUpperCase();
  const relScore = result.health.reliabilityScore ?? result.health.score;
  const relGrade = (result.health.reliabilityGrade ?? result.health.grade).toUpperCase();

  const lines: string[] = [
    "# 🩺 RepoDoctor Diagnostic Report",
    "",
    "| Metric | Value |",
    "| :--- | :--- |",
    `| **Status** | ${statusText} |`,
    `| **Health Score** | ${scorePercent} |`,
    `| **Security Score** | ${secScore}/100 (${secGrade}) |`,
    `| **Reliability Score** | ${relScore}/100 (${relGrade}) |`,
    `| **Critical Issues** | ${counts.critical} |`,
    `| **Warnings** | ${counts.warning} |`,
    `| **Suggestions / Info** | ${counts.info} |`,
    `| **Passing Checks** | ${counts.success} |`,
  ];

  if (result.coverage) {
    lines.push(
      `| **Files Scanned** | ${result.coverage.filesScanned} (${result.coverage.filesSkipped} skipped) |`,
      `| **Scan Duration** | ${result.coverage.durationMs}ms |`,
    );
  }

  lines.push("");

  if (issues.length > 0) {
    lines.push("### ⚠️ Findings & Recommendations", "");
    lines.push("| Severity | Category / Check | Issue | Recommendation |");
    lines.push("| :--- | :--- | :--- | :--- |");

    for (const item of issues) {
      const badge = severityBadge(item.severity);
      const title = cleanCell(item.title);
      const msg = cleanCell(item.message);
      const rec = cleanCell(item.recommendation);
      lines.push(`| ${badge} | ${title} | ${msg} | ${rec} |`);
    }
    lines.push("");
  } else {
    lines.push("> 🚀 **All systems green!** No issues, secret leaks, or vulnerabilities detected.", "");
  }

  if (passed.length > 0) {
    lines.push("<details>", `<summary><b>Passed Checks (${passed.length})</b></summary>`, "");
    for (const item of passed) {
      lines.push(`- ✅ **${cleanCell(item.title)}**${item.message ? `: ${cleanCell(item.message)}` : ""}`);
    }
    lines.push("", "</details>", "");
  }

  lines.push("---");
  lines.push("*Generated by [RepoDoctor](https://github.com/sandrotonal/repodoctor) — Enterprise Repository Diagnostics & Health Engine*");

  return lines.join("\n") + "\n";
}
