import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import type { Diagnostic } from "./core/types.js";
import { parseEnvKeys } from "./detectors/env.js";

export interface FixReport {
  applied: string[];
}

async function readOr(root: string, name: string): Promise<string | null> {
  try {
    return await readFile(path.join(root, name), "utf8");
  } catch {
    return null;
  }
}

async function ensureGitIgnoreEnv(root: string): Promise<boolean> {
  const file = path.join(root, ".gitignore");
  const existing = await readOr(root, ".gitignore");
  if (existing !== null && /\.env/.test(existing)) {
    return false;
  }
  const addition = `${existing !== null ? (existing.endsWith("\n") ? "" : "\n") : ""}.env\n.env.local\n`;
  await writeFile(file, `${existing ?? ""}${addition}`, "utf8");
  return true;
}

async function createEnvFromExample(root: string): Promise<boolean> {
  const example = await readOr(root, ".env.example");
  const env = await readOr(root, ".env");
  if (example === null || env !== null) {
    return false;
  }
  const keys = parseEnvKeys(example);
  const content = `# Generated by RepoDoctor from .env.example\n${keys.map((key) => `${key}=\n`).join("")}`;
  await writeFile(path.join(root, ".env"), content, "utf8");
  return true;
}

export async function applyFixes(root: string, diagnostics: Diagnostic[]): Promise<FixReport> {
  const applied: string[] = [];

  for (const diagnostic of diagnostics) {
    if (diagnostic.id === "env.not-gitignored") {
      if (await ensureGitIgnoreEnv(root)) {
        applied.push("Added .env and .env.local to .gitignore");
      }
    } else if (diagnostic.id === "env.missing") {
      if (await createEnvFromExample(root)) {
        applied.push("Created .env from .env.example template");
      }
    }
  }

  return { applied };
}