import { lstat, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import type { Diagnostic } from "./core/types.js";
import { parseEnvKeys } from "./detectors/env.js";

export interface FixDiff {
  file: string;
  diff: string;
}

export interface FixReport {
  applied: string[];
  diffs: FixDiff[];
}

export interface FixOptions {
  dryRun?: boolean;
}

export function isPathSafe(root: string, targetPath: string): boolean {
  const resolvedRoot = path.resolve(root);
  const resolvedTarget = path.resolve(targetPath);
  return resolvedTarget.startsWith(resolvedRoot + path.sep) || resolvedTarget === resolvedRoot;
}

export async function isSymlinkSafe(targetPath: string): Promise<boolean> {
  try {
    const stats = await lstat(targetPath);
    if (stats.isSymbolicLink()) {
      return false;
    }
  } catch {
    // File doesn't exist yet
  }
  return true;
}

export function createUnifiedDiff(filename: string, oldContent: string | null, newContent: string): string {
  const normFilename = filename.replace(/\\/g, "/");
  const oldLines = oldContent !== null ? oldContent.split(/\r?\n/) : [];
  const newLines = newContent.split(/\r?\n/);
  const diffLines: string[] = [`--- a/${normFilename}`, `+++ b/${normFilename}`];

  if (oldContent === null) {
    diffLines.push(`@@ -0,0 +1,${newLines.length} @@`);
    for (const line of newLines) {
      diffLines.push(`+${line}`);
    }
  } else {
    diffLines.push(`@@ -1,${oldLines.length} +1,${newLines.length} @@`);
    for (const line of oldLines) {
      if (!newLines.includes(line)) {
        diffLines.push(`-${line}`);
      }
    }
    for (const line of newLines) {
      if (!oldLines.includes(line)) {
        diffLines.push(`+${line}`);
      }
    }
  }
  return diffLines.join("\n");
}

async function readOr(root: string, name: string): Promise<string | null> {
  const fullPath = path.join(root, name);
  if (!isPathSafe(root, fullPath)) return null;
  try {
    return await readFile(fullPath, "utf8");
  } catch {
    return null;
  }
}

async function safeWrite(root: string, relPath: string, newContent: string, dryRun: boolean): Promise<boolean> {
  const fullPath = path.join(root, relPath);
  if (!isPathSafe(root, fullPath)) return false;
  if (!(await isSymlinkSafe(fullPath))) return false;

  if (!dryRun) {
    await writeFile(fullPath, newContent, "utf8");
  }
  return true;
}

async function ensureGitIgnoreEntries(
  root: string,
  entries: string[],
  dryRun: boolean,
): Promise<{ applied: boolean; diff?: FixDiff }> {
  const targetPath = path.join(root, ".gitignore");
  if (!isPathSafe(root, targetPath) || !(await isSymlinkSafe(targetPath))) {
    return { applied: false };
  }

  const existing = await readOr(root, ".gitignore");
  const lines = existing ? existing.split(/\r?\n/).map((l) => l.trim()) : [];

  const toAdd = entries.filter((entry) => !lines.includes(entry));
  if (toAdd.length === 0) {
    return { applied: false };
  }

  const prefix = existing !== null ? (existing.endsWith("\n") ? "" : "\n") : "";
  const addition = toAdd.join("\n") + "\n";
  const newContent = `${existing ?? ""}${prefix}${addition}`;

  const diff = {
    file: ".gitignore",
    diff: createUnifiedDiff(".gitignore", existing, newContent),
  };

  const ok = await safeWrite(root, ".gitignore", newContent, dryRun);
  return { applied: ok, diff };
}

async function createEnvFromExample(
  root: string,
  dryRun: boolean,
): Promise<{ applied: boolean; diff?: FixDiff }> {
  const example = await readOr(root, ".env.example");
  const env = await readOr(root, ".env");
  if (example === null || env !== null) {
    return { applied: false };
  }
  const keys = parseEnvKeys(example);
  const newContent = `# Generated by RepoDoctor from .env.example\n${keys.map((key) => `${key}=\n`).join("")}`;
  const diff = {
    file: ".env",
    diff: createUnifiedDiff(".env", null, newContent),
  };
  const ok = await safeWrite(root, ".env", newContent, dryRun);
  return { applied: ok, diff };
}

async function createExampleFromEnv(
  root: string,
  dryRun: boolean,
): Promise<{ applied: boolean; diff?: FixDiff }> {
  const env = await readOr(root, ".env");
  const example = await readOr(root, ".env.example");
  if (env === null || example !== null) {
    return { applied: false };
  }
  const keys = parseEnvKeys(env);
  if (keys.length === 0) {
    return { applied: false };
  }
  const newContent = `# Generated by RepoDoctor from local .env template\n${keys.map((key) => `${key}=\n`).join("")}`;
  const diff = {
    file: ".env.example",
    diff: createUnifiedDiff(".env.example", null, newContent),
  };
  const ok = await safeWrite(root, ".env.example", newContent, dryRun);
  return { applied: ok, diff };
}

async function ensureDockerignore(
  root: string,
  dryRun: boolean,
): Promise<{ applied: boolean; diff?: FixDiff }> {
  const existing = await readOr(root, ".dockerignore");
  const required = ["node_modules", ".env", ".env.local", ".git", "dist", "build"];

  const lines = existing ? existing.split(/\r?\n/).map((l) => l.trim()) : [];
  const toAdd = required.filter((r) => !lines.includes(r));
  if (toAdd.length === 0) {
    return { applied: false };
  }

  const prefix = existing !== null ? (existing.endsWith("\n") ? "" : "\n") : "";
  const addition = toAdd.join("\n") + "\n";
  const newContent = `${existing ?? ""}${prefix}${addition}`;
  const diff = {
    file: ".dockerignore",
    diff: createUnifiedDiff(".dockerignore", existing, newContent),
  };
  const ok = await safeWrite(root, ".dockerignore", newContent, dryRun);
  return { applied: ok, diff };
}

async function createMinimalTsConfig(
  root: string,
  dryRun: boolean,
): Promise<{ applied: boolean; diff?: FixDiff }> {
  const existing = await readOr(root, "tsconfig.json");
  if (existing !== null) return { applied: false };

  const newContent =
    JSON.stringify(
      {
        compilerOptions: {
          target: "ES2022",
          module: "NodeNext",
          moduleResolution: "NodeNext",
          esModuleInterop: true,
          strict: true,
          skipLibCheck: true,
        },
        include: ["src/**/*"],
      },
      null,
      2,
    ) + "\n";
  const diff = {
    file: "tsconfig.json",
    diff: createUnifiedDiff("tsconfig.json", null, newContent),
  };
  const ok = await safeWrite(root, "tsconfig.json", newContent, dryRun);
  return { applied: ok, diff };
}

async function createMinimalTailwindConfig(
  root: string,
  dryRun: boolean,
): Promise<{ applied: boolean; diff?: FixDiff }> {
  const existing = await readOr(root, "tailwind.config.js");
  if (existing !== null) return { applied: false };

  const newContent = `/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx,vue,svelte}"],
  theme: {
    extend: {},
  },
  plugins: [],
};
`;
  const diff = {
    file: "tailwind.config.js",
    diff: createUnifiedDiff("tailwind.config.js", null, newContent),
  };
  const ok = await safeWrite(root, "tailwind.config.js", newContent, dryRun);
  return { applied: ok, diff };
}

export async function applyFixes(
  root: string,
  diagnostics: Diagnostic[],
  options: FixOptions = {},
): Promise<FixReport> {
  const applied: string[] = [];
  const diffs: FixDiff[] = [];
  const dryRun = !!options.dryRun;

  for (const diagnostic of diagnostics) {
    if (diagnostic.id === "env.not-gitignored") {
      const res = await ensureGitIgnoreEntries(root, [".env", ".env.local"], dryRun);
      if (res.applied) {
        applied.push("Added .env and .env.local to .gitignore");
        if (res.diff) diffs.push(res.diff);
      }
    } else if (diagnostic.id === "env.missing") {
      const res = await createEnvFromExample(root, dryRun);
      if (res.applied) {
        applied.push("Created .env from .env.example template");
        if (res.diff) diffs.push(res.diff);
      }
    } else if (diagnostic.id === "env.example-missing") {
      const res = await createExampleFromEnv(root, dryRun);
      if (res.applied) {
        applied.push("Generated .env.example with placeholder keys from .env");
        if (res.diff) diffs.push(res.diff);
      }
    } else if (
      diagnostic.id === "docker.missing-dockerignore" ||
      diagnostic.id === "docker.dockerignore-incomplete"
    ) {
      const res = await ensureDockerignore(root, dryRun);
      if (res.applied) {
        applied.push("Configured .dockerignore to exclude node_modules, .env, and .git");
        if (res.diff) diffs.push(res.diff);
      }
    } else if (diagnostic.id === "typescript.missing-config") {
      const res = await createMinimalTsConfig(root, dryRun);
      if (res.applied) {
        applied.push("Created default tsconfig.json");
        if (res.diff) diffs.push(res.diff);
      }
    } else if (diagnostic.id === "framework.tailwind.missing-config") {
      const res = await createMinimalTailwindConfig(root, dryRun);
      if (res.applied) {
        applied.push("Created default tailwind.config.js");
        if (res.diff) diffs.push(res.diff);
      }
    } else if (diagnostic.id.startsWith("security.exposed-file:")) {
      const fileName = diagnostic.id.split(":")[1];
      // Guard against path traversal in rule IDs
      if (fileName && !fileName.includes("..") && !fileName.includes("/") && !fileName.includes("\\")) {
        const res = await ensureGitIgnoreEntries(root, [fileName], dryRun);
        if (res.applied) {
          applied.push(`Added sensitive file '${fileName}' to .gitignore`);
          if (res.diff) diffs.push(res.diff);
        }
      }
    }
  }

  return {
    applied: [...new Set(applied)],
    diffs,
  };
}