import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import type { Diagnostic } from "./core/types.js";
import { parseEnvKeys } from "./detectors/env.js";

export interface FixReport {
  applied: string[];
}

async function readOr(root: string, name: string): Promise<string | null> {
  try {
    return await readFile(path.join(root, name), "utf8");
  } catch {
    return null;
  }
}

async function ensureGitIgnoreEntries(root: string, entries: string[]): Promise<boolean> {
  const file = path.join(root, ".gitignore");
  const existing = await readOr(root, ".gitignore");
  const lines = existing ? existing.split(/\r?\n/).map((l) => l.trim()) : [];

  const toAdd = entries.filter((entry) => !lines.includes(entry));
  if (toAdd.length === 0) {
    return false;
  }

  const prefix = existing !== null ? (existing.endsWith("\n") ? "" : "\n") : "";
  const addition = toAdd.join("\n") + "\n";
  await writeFile(file, `${existing ?? ""}${prefix}${addition}`, "utf8");
  return true;
}

async function createEnvFromExample(root: string): Promise<boolean> {
  const example = await readOr(root, ".env.example");
  const env = await readOr(root, ".env");
  if (example === null || env !== null) {
    return false;
  }
  const keys = parseEnvKeys(example);
  const content = `# Generated by RepoDoctor from .env.example\n${keys.map((key) => `${key}=\n`).join("")}`;
  await writeFile(path.join(root, ".env"), content, "utf8");
  return true;
}

async function createExampleFromEnv(root: string): Promise<boolean> {
  const env = await readOr(root, ".env");
  const example = await readOr(root, ".env.example");
  if (env === null || example !== null) {
    return false;
  }
  const keys = parseEnvKeys(env);
  if (keys.length === 0) {
    return false;
  }
  const content = `# Generated by RepoDoctor from local .env template\n${keys.map((key) => `${key}=\n`).join("")}`;
  await writeFile(path.join(root, ".env.example"), content, "utf8");
  return true;
}

async function ensureDockerignore(root: string): Promise<boolean> {
  const file = path.join(root, ".dockerignore");
  const existing = await readOr(root, ".dockerignore");
  const required = ["node_modules", ".env", ".env.local", ".git", "dist", "build"];

  const lines = existing ? existing.split(/\r?\n/).map((l) => l.trim()) : [];
  const toAdd = required.filter((r) => !lines.includes(r));
  if (toAdd.length === 0) {
    return false;
  }

  const prefix = existing !== null ? (existing.endsWith("\n") ? "" : "\n") : "";
  const addition = toAdd.join("\n") + "\n";
  await writeFile(file, `${existing ?? ""}${prefix}${addition}`, "utf8");
  return true;
}

async function createMinimalTsConfig(root: string): Promise<boolean> {
  const tsconfigPath = path.join(root, "tsconfig.json");
  const existing = await readOr(root, "tsconfig.json");
  if (existing !== null) return false;

  const content =
    JSON.stringify(
      {
        compilerOptions: {
          target: "ES2022",
          module: "NodeNext",
          moduleResolution: "NodeNext",
          esModuleInterop: true,
          strict: true,
          skipLibCheck: true,
        },
        include: ["src/**/*"],
      },
      null,
      2,
    ) + "\n";

  await writeFile(tsconfigPath, content, "utf8");
  return true;
}

async function createMinimalTailwindConfig(root: string): Promise<boolean> {
  const configFile = path.join(root, "tailwind.config.js");
  const existing = await readOr(root, "tailwind.config.js");
  if (existing !== null) return false;

  const content = `/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx,vue,svelte}"],
  theme: {
    extend: {},
  },
  plugins: [],
};
`;
  await writeFile(configFile, content, "utf8");
  return true;
}

export async function applyFixes(root: string, diagnostics: Diagnostic[]): Promise<FixReport> {
  const applied: string[] = [];

  for (const diagnostic of diagnostics) {
    if (diagnostic.id === "env.not-gitignored") {
      if (await ensureGitIgnoreEntries(root, [".env", ".env.local"])) {
        applied.push("Added .env and .env.local to .gitignore");
      }
    } else if (diagnostic.id === "env.missing") {
      if (await createEnvFromExample(root)) {
        applied.push("Created .env from .env.example template");
      }
    } else if (diagnostic.id === "env.example-missing") {
      if (await createExampleFromEnv(root)) {
        applied.push("Generated .env.example with placeholder keys from .env");
      }
    } else if (
      diagnostic.id === "docker.missing-dockerignore" ||
      diagnostic.id === "docker.dockerignore-incomplete"
    ) {
      if (await ensureDockerignore(root)) {
        applied.push("Configured .dockerignore to exclude node_modules, .env, and .git");
      }
    } else if (diagnostic.id === "typescript.missing-config") {
      if (await createMinimalTsConfig(root)) {
        applied.push("Created default tsconfig.json");
      }
    } else if (diagnostic.id === "framework.tailwind.missing-config") {
      if (await createMinimalTailwindConfig(root)) {
        applied.push("Created default tailwind.config.js");
      }
    } else if (diagnostic.id.startsWith("security.exposed-file:")) {
      const fileName = diagnostic.id.split(":")[1];
      if (fileName && (await ensureGitIgnoreEntries(root, [fileName]))) {
        applied.push(`Added sensitive file '${fileName}' to .gitignore`);
      }
    }
  }

  return { applied: [...new Set(applied)] };
}